FROM ubuntu:latest
EXPOSE 5000
ENV FLASH_APP="filmlog"
ENV FLASK_DEBUG=1

RUN apt-get update -y && \
    apt-get install -y python-pip python-dev build-essential mariadb-client-10.0 libmysqlclient-dev

COPY requirements.txt /
RUN pip install -r requirements.txt
COPY . /srv/filmlog.org
WORKDIR /srv/filmlog.org
CMD python wsgi.py
#CMD flask run --host=0.0.0.0
#CMD ./run.sh
#CMD ./wsgi.sh
#RUN pip install -r requirements.txt
#RUN useradd -d /srv/filmlog.org filmlog
#RUN chown -R filmlog:www-data /srv/filmlog.org
#RUN python setup.py develop
#CMD /usr/sbin/apache2ctl -D FOREGROUND
